"""Router assembly for Phase 2 segmentation routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/init.ipynb.

# %% auto #0
__all__ = ['WrappedHandlers', 'compute_segmentation_urls', 'init_segmentation_routers']

# %% ../../nbs/routes/init.ipynb #c3d4e5f6
from typing import List, Dict, Callable, Tuple, Optional

from cjm_fasthtml_app_core.core.routing import APIRouter

from cjm_fasthtml_card_stack.core.models import CardStackUrls

from ..models import SegmentationUrls
from cjm_transcript_segmentation.routes.core import (
    WorkflowStateStore, DEFAULT_MAX_HISTORY_DEPTH,
)
from .card_stack import init_card_stack_router
from .handlers import init_workflow_router
from ..services.segmentation import SegmentationService
from cjm_transcript_source_select.services.source import SourceService


# Type alias for wrapped handlers dict
WrappedHandlers = Dict[str, Callable]

# %% ../../nbs/routes/init.ipynb #c60faf59
def compute_segmentation_urls(
    prefix:str,  # Base prefix for segmentation routes (e.g., "/workflow/seg")
) -> SegmentationUrls:  # Fully populated URL bundle (no routes registered)
    """Compute the URL bundle for segmentation routes from a prefix.

    Returns the same SegmentationUrls that `init_segmentation_routers(prefix=prefix)`
    would populate, without registering any routes. Lets consumers (e.g., page-centric
    libraries that wrap segmentation) build wrapped handlers BEFORE calling
    init_segmentation_routers, resolving the chicken-and-egg dependency between
    URL bundle and wrapper construction.

    The URL conventions encoded here are the public contract of init_segmentation_routers
    and stay synchronized via the test cell below.
    """
    cs_prefix = f"{prefix}/card_stack"
    wf_prefix = f"{prefix}/workflow"
    return SegmentationUrls(
        card_stack=CardStackUrls(
            nav_up=f"{cs_prefix}/nav_up",
            nav_down=f"{cs_prefix}/nav_down",
            nav_first=f"{cs_prefix}/nav_first",
            nav_last=f"{cs_prefix}/nav_last",
            nav_page_up=f"{cs_prefix}/nav_page_up",
            nav_page_down=f"{cs_prefix}/nav_page_down",
            nav_to_index=f"{cs_prefix}/nav_to_index",
            update_viewport=f"{cs_prefix}/update_viewport",
            save_width=f"{cs_prefix}/save_width",
        ),
        enter_split=f"{cs_prefix}/enter_split",
        exit_split=f"{cs_prefix}/exit_split",
        init=f"{wf_prefix}/init",
        split=f"{wf_prefix}/split",
        merge=f"{wf_prefix}/merge",
        undo=f"{wf_prefix}/undo",
        reset=f"{wf_prefix}/reset",
        ai_split=f"{wf_prefix}/ai_split",
    )

# %% ../../nbs/routes/init.ipynb #e5f6a7b8
def init_segmentation_routers(
    state_store:WorkflowStateStore,  # The workflow state store
    workflow_id:str,  # The workflow identifier
    source_service:SourceService,  # Service for fetching source blocks
    segmentation_service:SegmentationService,  # Service for NLTK sentence splitting
    prefix:str,  # Base prefix for segmentation routes (e.g., "/workflow/seg")
    max_history_depth:int=DEFAULT_MAX_HISTORY_DEPTH,  # Maximum history stack depth
    wrapped_handlers:WrappedHandlers=None,  # Dict with 'init', 'split', 'merge', 'undo', 'reset', 'ai_split' keys
    urls:Optional[SegmentationUrls]=None,  # Pre-populated URL bundle (e.g., from compute_segmentation_urls); created if None
) -> Tuple[List[APIRouter], SegmentationUrls, Dict[str, Callable]]:  # (routers, urls, merged_routes)
    """Initialize and return all segmentation routers with URL bundle.

    The wrapped_handlers dict should contain handlers that already have
    cross-domain concerns (KB system, alignment status) handled by the
    combined layer's wrapper factories.

    The `urls` parameter accepts a pre-populated SegmentationUrls (typically from
    `compute_segmentation_urls(prefix)`) so consumers can build wrapped handlers
    that need URLs before init_segmentation_routers runs. Default behavior
    (urls=None) is unchanged from before — an empty SegmentationUrls is created
    internally and populated after routes are registered.
    """
    # Create empty URL bundle (populated after routes are defined) unless caller provides one.
    # Caller-provided urls fields get overwritten with the same values
    # (the URL convention in compute_segmentation_urls is the public contract of this function).
    if urls is None:
        urls = SegmentationUrls()
    wrapped_handlers = wrapped_handlers or {}

    # Initialize focused routers
    card_stack_router, card_stack_routes = init_card_stack_router(
        state_store, workflow_id, f"{prefix}/card_stack", urls
    )
    workflow_router, workflow_routes = init_workflow_router(
        state_store, workflow_id,
        source_service, segmentation_service,
        f"{prefix}/workflow", urls,
        max_history_depth=max_history_depth,
        handler_init=wrapped_handlers.get("init"),
        handler_split=wrapped_handlers.get("split"),
        handler_merge=wrapped_handlers.get("merge"),
        handler_undo=wrapped_handlers.get("undo"),
        handler_reset=wrapped_handlers.get("reset"),
        handler_ai_split=wrapped_handlers.get("ai_split"),
    )

    # Populate the URL bundle using .to() on route functions
    urls.card_stack = CardStackUrls(
        nav_up=card_stack_routes["nav_up"].to(),
        nav_down=card_stack_routes["nav_down"].to(),
        nav_first=card_stack_routes["nav_first"].to(),
        nav_last=card_stack_routes["nav_last"].to(),
        nav_page_up=card_stack_routes["nav_page_up"].to(),
        nav_page_down=card_stack_routes["nav_page_down"].to(),
        nav_to_index=card_stack_routes["nav_to_index"].to(),
        update_viewport=card_stack_routes["update_viewport"].to(),
        save_width=card_stack_routes["save_width"].to(),
    )
    urls.enter_split = card_stack_routes["enter_split"].to()
    urls.exit_split = card_stack_routes["exit_split"].to()
    urls.init = workflow_routes["init"].to()
    urls.split = workflow_routes["split"].to()
    urls.merge = workflow_routes["merge"].to()
    urls.undo = workflow_routes["undo"].to()
    urls.reset = workflow_routes["reset"].to()
    urls.ai_split = workflow_routes["ai_split"].to()

    # Merge all routes for external access
    merged_routes = {
        **card_stack_routes,
        **workflow_routes,
    }

    routers = [card_stack_router, workflow_router]

    return routers, urls, merged_routes
