"""Card stack configuration constants for the Phase 2 segmentation UI"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/card_stack_config.ipynb.

# %% auto #0
__all__ = ['SEG_CS_CONFIG', 'SEG_CS_IDS', 'SEG_CS_BTN_IDS', 'SEG_TS_CONFIG', 'SEG_TS_IDS']

# %% ../../nbs/components/card_stack_config.ipynb #cs-cfg-constants
from cjm_fasthtml_card_stack.core.config import CardStackConfig, CardStackStyleConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds

from cjm_fasthtml_token_selector.core.config import TokenSelectorConfig
from cjm_fasthtml_token_selector.core.html_ids import TokenSelectorHtmlIds

SEG_CS_CONFIG = CardStackConfig(
    prefix="sd-seg",
    disable_scroll_in_modes=("split",),
    style=CardStackStyleConfig(
        viewport_padding_x='0.0rem', 
        viewport_padding_y='0.0rem'
    )
)

SEG_CS_IDS = CardStackHtmlIds(prefix=SEG_CS_CONFIG.prefix)
SEG_CS_BTN_IDS = CardStackButtonIds(prefix=SEG_CS_CONFIG.prefix)

SEG_TS_CONFIG = TokenSelectorConfig(
    prefix="sd-seg-ts",
    selection_mode="gap",
    initial_delay=200,
    repeat_interval=90,
    throttle_floor=50,
)

SEG_TS_IDS = TokenSelectorHtmlIds(prefix=SEG_TS_CONFIG.prefix)
