"""HTML ID constants for Phase 2 Left Column: Text Segmentation"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['SegmentationHtmlIds']

# %% ../nbs/html_ids.ipynb #c3d4e5f6
# Framework-agnostic — no external imports needed

class SegmentationHtmlIds:
    """HTML ID constants for Phase 2 Left Column: Text Segmentation."""

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Column Layout (used by combined layer but owned here)
    COLUMN_CONTENT = "sd-seg-column-content"  # Column body content area
    MINI_STATS = "sd-seg-mini-stats"  # Mini stats badge in column header

    # Main Layout
    # (Card stack IDs provided by CardStackHtmlIds from cjm-fasthtml-card-stack)
    # (Token selector IDs provided by TokenSelectorHtmlIds from cjm-fasthtml-token-selector)
    SEG_CONTAINER = "sd-seg-container"
    SEG_HEADER = "sd-seg-header"
    SEG_FOOTER = "sd-seg-footer"
    SEG_STATS = "sd-seg-stats"

    # Toolbar
    # (Undo button ID is owned by the keyboard system — see SD_SEG_UNDO_BTN in keyboard_config)
    SEG_TOOLBAR = "sd-seg-toolbar"
    SEG_RESET_BTN = "sd-seg-reset-btn"
    SEG_AI_SPLIT_BTN = "sd-seg-ai-split-btn"

    # Split Mode
    SPLIT_MODE_CONTAINER = "sd-split-mode-container"
    SPLIT_MODE_ACTIONS = "sd-split-mode-actions"

    @staticmethod
    def segment_card(
        index:int  # Segment index in the decomposition
    ) -> str:  # HTML ID for the segment card
        """Generate HTML ID for a segment card."""
        return f"sd-segment-card-{index}"
