"""Text processing utilities for segmentation: word counting, position mapping, and statistics"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['count_words', 'word_index_to_char_position', 'calculate_segment_stats']

# %% ../nbs/utils.ipynb #seg-utils-imports
from typing import List, Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from cjm_transcript_segmentation.models import TextSegment

# %% ../nbs/utils.ipynb #seg-utils-count-words
def count_words(
    text: str  # Text to count words in
) -> int:  # Word count
    """Count the number of whitespace-delimited words in text."""
    if not text:
        return 0
    return len(text.split())

# %% ../nbs/utils.ipynb #seg-utils-word-index-to-char
def word_index_to_char_position(
    text: str,  # Full text
    word_index: int  # Word index (0-based, split happens before this word)
) -> int:  # Character position for split
    """Convert a word index to the character position where a split should occur."""
    if word_index <= 0:
        return 0
    
    words = text.split()
    if word_index >= len(words):
        return len(text)
    
    # Find the character position before the word at word_index
    position = 0
    for i, word in enumerate(words):
        if i == word_index:
            break
        position += len(word)
        # Account for space after word (except for last word before split)
        if i < word_index - 1 or i < len(words) - 1:
            # Find the actual space position in text
            while position < len(text) and text[position] == ' ':
                position += 1
    
    return position

# %% ../nbs/utils.ipynb #seg-utils-calc-stats
def calculate_segment_stats(
    segments: List["TextSegment"]  # List of segments to analyze
) -> Dict[str, Any]:  # Statistics dictionary with total_words, total_segments
    """Calculate aggregate statistics for a list of segments."""
    total_words = sum(count_words(s.text) for s in segments)
    total_segments = len(segments)
    
    return {
        "total_words": total_words,
        "total_segments": total_segments,
    }
